### PR TITLE
fixes #4

### LINKED ISSUE #4: assertThrows raise an exception about mismatching messages
There is an example to reproduce:
```php
$this->assertThrows(Exception::class, function () {
    throw new Exception('an exception');
});
```
`exception message '' was expected, but 'an exception' was received`

### PR DESCRIPTION
**Pull request by askobara**
Fixes #4

### CODE REVIEW

**Review by AlexSkrypnyk — APPROVED** [review]

**Comment by mbicknese** [comment]
Please merge this as the package is currently unusable if you don't care about the message. And `specify` dropped support for handling exceptions.

**Comment by barthy-koeln** [comment]
This assertion loses its value without this fix.

Currently, you would have to define a message in the assertion in order for it to pass. At the same time, this message is being transformed to lowercase, so the actual thrown exception has to be lowercase, too.

Please merge it! :+1:

**Comment by VincentClair** [comment]
@DavertMik please ?

**Comment by wmathes** [comment]
No chance... the maintainers don't care about this :) Complete ignorance.

**Pull request merged**
